name: "Build Images"

on: workflow_dispatch
# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

jobs:
  test:
    name: Build
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Build
        run: echo "oi eu sou goku" 
